# Generated by Django 4.1.4 on 2022-12-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IshHolati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuklanganvagon', models.CharField(max_length=250)),
                ('yuklanishunturganvagon', models.CharField(max_length=250)),
                ('tushurilganvagonlar', models.CharField(max_length=250)),
                ('tushurishunturganvagon', models.CharField(max_length=250)),
                ('bushvagon', models.CharField(max_length=250)),
                ('mdhvagon', models.CharField(max_length=250)),
            ],
        ),
    ]
