# Generated by Django 4.1.4 on 2022-12-27 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainstatus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stansiyalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yulak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yulak', models.CharField(help_text='Turgan yulak nomi', max_length=5, unique=True)),
                ('holati', models.CharField(blank=True, choices=[("BO'SH", 'BO`SH'), ('TAYYOR', 'TAYYOR')], help_text='Yulak holatni tanlang ', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('go_to', models.ForeignKey(blank=True, help_text='Junab ketadigan stansiya aha', null=True, on_delete=django.db.models.deletion.CASCADE, to='trainstatus.stansiyalar')),
                ('stansiya', models.ForeignKey(help_text='Tirgan stansiya nomi', on_delete=django.db.models.deletion.CASCADE, related_name='stansiya', to='trainstatus.stansiyalar')),
            ],
        ),
    ]
