# Generated by Django 4.1.5 on 2023-01-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainstatus', '0002_stansiyalar_yulak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishholati',
            name='bushvagon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ishholati',
            name='mdhvagon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ishholati',
            name='tushurilganvagonlar',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ishholati',
            name='tushurishunturganvagon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ishholati',
            name='yuklanganvagon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ishholati',
            name='yuklanishunturganvagon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
